application: s~dan-bamberger 
version: 2
runtime: python27
threadsafe: no
api_version: 1

default_expiration: "1s"

handlers:
- url: /r
  static_dir: resources

- url: /editor
  static_files: editor/index.html
  upload: editor/index.html
  login: admin

- url: /items
  script: index.app
  login: admin

- url: .*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on
